### ISSUE TITLE
[Feature Request] trade DCA

### ISSUE THREAD

**Issue by chanonong** [dusktrades/ftx-cli#51]
I would like to request a feature to create multiple orders within the price range
e.g. `ftx trade --market AVAX-PERP --side buy --type limit --size 2000 --price 103.65 --dca 10 --dca-to 102.5`
would place limit order like this
```
103.6500 -- 200.0
103.5222 -- 200.0
103.3944 -- 200.0
103.2667 -- 200.0
103.1389 -- 200.0
103.0111 -- 200.0
102.8833 -- 200.0
102.7556 -- 200.0
102.6278 -- 200.0
102.5000 -- 200.0
```
![image](https://user-images.githubusercontent.com/867676/147776064-565579ea-1980-43dd-8c46-170c11342309.png)

**Comment by dusktrades** [comment]
Hi, you can achieve this by using [scaled prices](https://github.com/dusktrades/ftx-cli/blob/master/docs/topics/trading/order-pricing.md#scaled-price).

The command for your example would be:

```sh
ftx trade --market AVAX-PERP --side buy --type limit --size 2000 --price 103.65:102.5 --split 10
```
